-- SDK 核心表结构（H2 测试版本）
-- 用于单元测试，零外部数据库依赖

-- 1. 支付记录表
CREATE TABLE IF NOT EXISTS sdk_payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_order_no VARCHAR(64) NOT NULL,
    payment_no VARCHAR(64) NOT NULL,
    channel_code VARCHAR(32) NOT NULL,
    paid_amount DECIMAL(18,2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sdk_payment_record_payment_no ON sdk_payment_record(payment_no);
CREATE INDEX IF NOT EXISTS idx_sdk_payment_record_order_no ON sdk_payment_record(biz_order_no);

-- 2. 幂等记录表
CREATE TABLE IF NOT EXISTS sdk_idempotent_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scene_code VARCHAR(32) NOT NULL,
    idempotent_key VARCHAR(128) NOT NULL,
    biz_order_no VARCHAR(64),
    task_no VARCHAR(64),
    task_id BIGINT,
    status VARCHAR(32) NOT NULL,
    expired_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sdk_idempotent_scene_key ON sdk_idempotent_record(scene_code, idempotent_key);

-- 3. 发放任务表
CREATE TABLE IF NOT EXISTS sdk_fulfillment_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(64) NOT NULL,
    biz_order_no VARCHAR(64) NOT NULL,
    biz_user_ref VARCHAR(64) NOT NULL,
    benefit_type_code VARCHAR(32) NOT NULL,
    action_code VARCHAR(32) NOT NULL DEFAULT 'GRANT',
    benefit_config_snapshot CLOB NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 3,
    last_error_code VARCHAR(64),
    last_error_msg VARCHAR(512),
    next_retry_at TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sdk_fulfillment_task_task_no ON sdk_fulfillment_task(task_no);
CREATE INDEX IF NOT EXISTS idx_sdk_fulfillment_task_order_no ON sdk_fulfillment_task(biz_order_no);
CREATE INDEX IF NOT EXISTS idx_sdk_fulfillment_task_status ON sdk_fulfillment_task(status);

-- 4. 发放日志表
CREATE TABLE IF NOT EXISTS sdk_fulfillment_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    action_code VARCHAR(32),
    handler_name VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    error_code VARCHAR(64),
    error_msg VARCHAR(512),
    result_summary VARCHAR(512),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    duration_ms BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sdk_fulfillment_log_task_id ON sdk_fulfillment_log(task_id);
